OZON_CLIENT_ID = '2663'
OZON_API_KEY = '236f59a6-0906-4ae8-8109-ae089a42c0b0'
# Api-Key из таблицы account_list соотв. client_id = '2663'
# 'a3924ac9-f3fe-45d3-ba53-ae91209a1e0b'
URL_OZON_STOCKS_FBS = 'https://api-seller.ozon.ru/v1/product/import/stocks'
URL_OZON_STOCKS = 'https://api-seller.ozon.ru/v2/products/stocks'
URL_OZON_PRICES = 'https://api-seller.ozon.ru/v1/product/import/prices'
URL_OZON_PRODUCTS = 'https://api-seller.ozon.ru/v2/product/list'
URL_OZON_PRODUCT_INFO = 'https://api-seller.ozon.ru/v2/product/info'
URL_OZON_WAREHOUSES = 'https://api-seller.ozon.ru/v1/warehouse/list'
URL_OZON_STOCKS_INFO = 'https://api-seller.ozon.ru/v3/product/info/stocks'