###
POST http://localhost:5000/stocks
Content-Type: application/json

{
  "warehouseId": 10000005,
  "partnerWarehouseId": "50",
  "skus": [
     "263507710",
      "263513205",
      "263513128",
      "263513419"
  ]
}