###
POST http://localhost:5000/stocks
Content-Type: application/json

{
"data":
  {
  "rule": 1,
  "marketplaces":
    [
      {
      "Marketplace": "Ozon",
      "Client-Id": "",
      "Api-Key": ""
      },
      {
      "Marketplace": "WB",
      "Api-Key": ""
      },
      ...
    ],
  "products":
    [
      {
        "product_id": 1176550,
        "barcode": "",
        "stock": 10,
        "warehouse_id": 23501632841000
      },
      {
        "product_id": 1176734,
        "barcode": "",
        "stock": 15,
        "warehouse_id": 23501632841000
      },
      ...
    ]
  }
}