###
POST http://localhost:5000/update
Content-Type: application/json
Api-Key: 123
Client-Id: 123

{
"data":
  {
    "marketplace": "Ozon",
    "products":
      [
        {
          "warehouse_id": 1,
          "product_id": 1,
          "price": 100,
          "stock": 10
        },
        {
          "warehouse_id": 2,
          "product_id": 2,
          "price": 200,
          "stock": 20
        }
      ]
  }
}